language: cpp

# 安装 CMake
before_install:
  - sudo apt-get update
  - sudo apt-get install -y cmake

# 构建和测试脚本
script:
  # 检查 build 目录是否存在，如果不存在则创建
  - if [ ! -d build ]; then mkdir build; fi
  - cd build

  # 使用 CMake 配置项目
  - cmake ..

  # 使用 make 编译项目
  - cmake --build .

  # 运行测试程序
  - cd ../bin
  - ./stltest
