version: 1.0.{build}
image: Ubuntu2004
install:
- cmd: >-
    sudo apt-get update


    sudo apt-get install -y cmake
build_script:
- cmd: >-
    cd build

    cmake ../

    cmake --build .
test_script:
- cmd: >-
    cd ../bin


    ./stltest