version: 1.0.{build}
image: Ubuntu2004
install:
# - sudo apt-get update
- echo "Hello, World!"
- sudo apt-get install -y cmake

build_script:
- mkdir build
- cd build
- cmake ../
- cmake --build .

test_script:
- cd ../bin
- ./stltest